services:
  # Frontend service (Static Site)
  - type: web
    name: kenya-finance-watch
    env: static
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: kenya-finance-watch/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 